"""add fit score columns

Revision ID: cbb8edcf0757
Revises: 381231f0c877
Create Date: 2026-06-05 15:27:19.821144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb8edcf0757'
down_revision: Union[str, Sequence[str], None] = '381231f0c877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('fit_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'fit_reason')
    op.drop_column('candidates', 'fit_score')
    # ### end Alembic commands ###
