"""create jobs table

Revision ID: f25baa93b067
Revises: 890ea0f9c6d2
Create Date: 2026-06-04 20:23:49.107566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f25baa93b067'
down_revision: Union[str, Sequence[str], None] = '890ea0f9c6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidates', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'job_id')
    # ### end Alembic commands ###
